USE [master]
GO

/*
  Favor actualizar las rutas "FILENAME", para el archivo .mdf y .log.
*/
CREATE DATABASE [EvertecPruebas]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EvertecPruebas', FILENAME = N'' /*Actualizar*/, SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EvertecPruebas_log', FILENAME = N''/*Actualizar*/ , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [EvertecPruebas] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EvertecPruebas].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EvertecPruebas] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EvertecPruebas] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EvertecPruebas] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EvertecPruebas] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EvertecPruebas] SET ARITHABORT OFF 
GO
ALTER DATABASE [EvertecPruebas] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [EvertecPruebas] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [EvertecPruebas] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EvertecPruebas] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EvertecPruebas] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [EvertecPruebas] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EvertecPruebas] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EvertecPruebas] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EvertecPruebas] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EvertecPruebas] SET  DISABLE_BROKER 
GO
ALTER DATABASE [EvertecPruebas] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EvertecPruebas] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EvertecPruebas] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [EvertecPruebas] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [EvertecPruebas] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EvertecPruebas] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [EvertecPruebas] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [EvertecPruebas] SET RECOVERY FULL 
GO
ALTER DATABASE [EvertecPruebas] SET  MULTI_USER 
GO
ALTER DATABASE [EvertecPruebas] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EvertecPruebas] SET DB_CHAINING OFF 
GO
ALTER DATABASE [EvertecPruebas] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [EvertecPruebas] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [EvertecPruebas] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [EvertecPruebas] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'EvertecPruebas', N'ON'
GO
ALTER DATABASE [EvertecPruebas] SET QUERY_STORE = OFF
GO
USE [EvertecPruebas]
GO
/****** Object:  Table [dbo].[EstadoCivil]    Script Date: 14/12/2022 5:37:19 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EstadoCivil](
	[IdEstadoCivil] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
 CONSTRAINT [PK_EstadoCivil] PRIMARY KEY CLUSTERED 
(
	[IdEstadoCivil] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 14/12/2022 5:37:19 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[IdUsuario] [int] IDENTITY(1,1) NOT NULL,
	[IdEstadoCivil] [int] NOT NULL,
	[PrimerNombre] [varchar](50) NOT NULL,
	[SegundoNombre] [varchar](50) NULL,
	[PrimerApellido] [varchar](50) NOT NULL,
	[SegundoApellido] [varchar](50) NULL,
	[FechaNacimiento] [date] NOT NULL,
	[TieneHermanos] [bit] NOT NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[IdUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Usuario]  WITH CHECK ADD  CONSTRAINT [FK_Usuario_EstadoCivil] FOREIGN KEY([IdEstadoCivil])
REFERENCES [dbo].[EstadoCivil] ([IdEstadoCivil])
GO
ALTER TABLE [dbo].[Usuario] CHECK CONSTRAINT [FK_Usuario_EstadoCivil]
GO
USE [master]
GO
ALTER DATABASE [EvertecPruebas] SET  READ_WRITE 
GO
/*Cargar información en tabla estados civiles*/
USE [EvertecPruebas]
GO
INSERT INTO [dbo].[EstadoCivil]
           ([Nombre])
     VALUES
           ('Soltero'), ('Casado')
GO
